from PyQt5 import QtCore, QtWidgets, QtChart

class Ui_SerialWidget(object):
    def setupUi(self, SerialWidget):
        SerialWidget.setObjectName("SerialWidget")
        SerialWidget.resize(600, 400)

        self.verticalLayout = QtWidgets.QVBoxLayout(SerialWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)

        self.topLayout = QtWidgets.QHBoxLayout()

        self.btnOnline = QtWidgets.QPushButton(SerialWidget)
        self.btnOnline.setObjectName("btnOnline")
        self.topLayout.addWidget(self.btnOnline)

        self.labelComPort = QtWidgets.QLabel(SerialWidget)
        self.labelComPort.setObjectName("labelComPort")
        self.topLayout.addWidget(self.labelComPort)

        self.comboPort = QtWidgets.QComboBox(SerialWidget)
        self.comboPort.setObjectName("comboPort")
        self.topLayout.addWidget(self.comboPort)

        self.btnConfigure = QtWidgets.QPushButton(SerialWidget)
        self.btnConfigure.setObjectName("btnConfigure")
        self.topLayout.addWidget(self.btnConfigure)

        self.labelFw = QtWidgets.QLabel(SerialWidget)
        self.labelFw.setObjectName("labelFw")
        self.topLayout.addWidget(self.labelFw)

        self.labelFwValue = QtWidgets.QLabel(SerialWidget)
        self.labelFwValue.setObjectName("labelFwValue")
        self.labelFwValue.setMinimumWidth(100)
        self.labelFwValue.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelFwValue.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.topLayout.addWidget(self.labelFwValue)

        self.verticalLayout.addLayout(self.topLayout)

        self.tabWidget = QtWidgets.QTabWidget(SerialWidget)
        self.tabWidget.setObjectName("tabWidget")

        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.horizontalMain = QtWidgets.QHBoxLayout(self.tabMain)
        self.horizontalMain.setObjectName("horizontalMain")

        self.groupPanTilt = QtWidgets.QGroupBox(self.tabMain)
        self.groupPanTilt.setObjectName("groupPanTilt")
        self.layoutPanTilt = QtWidgets.QVBoxLayout(self.groupPanTilt)
        self.layoutPanTilt.setObjectName("layoutPanTilt")
        self.groupMove = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupMove.setObjectName("groupMove")
        self.gridMove = QtWidgets.QGridLayout(self.groupMove)
        self.gridMove.setObjectName("gridMove")

        self.labelTarget = QtWidgets.QLabel(self.groupMove)
        self.labelTarget.setObjectName("labelTarget")
        self.gridMove.addWidget(self.labelTarget, 0, 0, 1, 1)
        self.spinTarget = QtWidgets.QSpinBox(self.groupMove)
        self.spinTarget.setObjectName("spinTarget")
        self.gridMove.addWidget(self.spinTarget, 0, 1, 1, 1)

        self.labelDome = QtWidgets.QLabel(self.groupMove)
        self.labelDome.setObjectName("labelDome")
        self.gridMove.addWidget(self.labelDome, 0, 2, 1, 1)
        self.spinDome = QtWidgets.QSpinBox(self.groupMove)
        self.spinDome.setObjectName("spinDome")
        self.gridMove.addWidget(self.spinDome, 0, 3, 1, 1)

        self.labelFunction = QtWidgets.QLabel(self.groupMove)
        self.labelFunction.setObjectName("labelFunction")
        self.gridMove.addWidget(self.labelFunction, 0, 4, 1, 1)
        self.spinFunction = QtWidgets.QSpinBox(self.groupMove)
        self.spinFunction.setObjectName("spinFunction")
        self.gridMove.addWidget(self.spinFunction, 0, 5, 1, 1)

        self.labelAlarmNumber = QtWidgets.QLabel(self.groupMove)
        self.labelAlarmNumber.setObjectName("labelAlarmNumber")
        self.gridMove.addWidget(self.labelAlarmNumber, 1, 0, 1, 1)
        self.comboAlarmNumber = QtWidgets.QComboBox(self.groupMove)
        self.comboAlarmNumber.setObjectName("comboAlarmNumber")
        self.gridMove.addWidget(self.comboAlarmNumber, 1, 1, 1, 1)

        self.labelAlarmType = QtWidgets.QLabel(self.groupMove)
        self.labelAlarmType.setObjectName("labelAlarmType")
        self.gridMove.addWidget(self.labelAlarmType, 1, 2, 1, 1)
        self.comboAlarmType = QtWidgets.QComboBox(self.groupMove)
        self.comboAlarmType.setObjectName("comboAlarmType")
        self.gridMove.addWidget(self.comboAlarmType, 1, 3, 1, 1)

        self.btnSetDefault = QtWidgets.QPushButton(self.groupMove)
        self.btnSetDefault.setObjectName("btnSetDefault")
        self.gridMove.addWidget(self.btnSetDefault, 2, 0, 1, 1)
        self.btnSetMove = QtWidgets.QPushButton(self.groupMove)
        self.btnSetMove.setObjectName("btnSetMove")
        self.gridMove.addWidget(self.btnSetMove, 2, 3, 1, 1)
        self.btnClearMove = QtWidgets.QPushButton(self.groupMove)
        self.btnClearMove.setObjectName("btnClearMove")
        self.gridMove.addWidget(self.btnClearMove, 2, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupMove)
        self.groupPanTilt.setLayout(self.layoutPanTilt)
        self.horizontalMain.addWidget(self.groupPanTilt)

        self.layoutChart = QtWidgets.QVBoxLayout()
        self.layoutChart.setObjectName("layoutChart")
        self.chartSpeed = QtChart.QChartView(self.tabMain)
        self.chartSpeed.setObjectName("chartSpeed")
        self.layoutChart.addWidget(self.chartSpeed)
        self.layoutChartButtons = QtWidgets.QHBoxLayout()
        self.layoutChartButtons.setObjectName("layoutChartButtons")
        self.btnShowSpeed = QtWidgets.QPushButton(self.tabMain)
        self.btnShowSpeed.setObjectName("btnShowSpeed")
        self.layoutChartButtons.addWidget(self.btnShowSpeed)
        self.btnStopSpeed = QtWidgets.QPushButton(self.tabMain)
        self.btnStopSpeed.setObjectName("btnStopSpeed")
        self.layoutChartButtons.addWidget(self.btnStopSpeed)
        self.layoutChart.addLayout(self.layoutChartButtons)
        self.horizontalMain.addLayout(self.layoutChart)

        self.tabWidget.addTab(self.tabMain, "")

        self.tabTest = QtWidgets.QWidget()
        self.tabTest.setObjectName("tabTest")
        self.verticalLayoutTest = QtWidgets.QVBoxLayout(self.tabTest)
        self.verticalLayoutTest.setObjectName("verticalLayoutTest")
        self.groupVisca = QtWidgets.QGroupBox(self.tabTest)
        self.groupVisca.setObjectName("groupVisca")
        self.gridVisca = QtWidgets.QGridLayout(self.groupVisca)
        self.gridVisca.setObjectName("gridVisca")

        self.btnTest1 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest1.setObjectName("btnTest1")
        self.gridVisca.addWidget(self.btnTest1, 0, 0, 1, 1)
        self.editTest1 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest1.setObjectName("editTest1")
        self.gridVisca.addWidget(self.editTest1, 0, 1, 1, 1)

        self.btnTest2 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest2.setObjectName("btnTest2")
        self.gridVisca.addWidget(self.btnTest2, 1, 0, 1, 1)
        self.editTest2 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest2.setObjectName("editTest2")
        self.gridVisca.addWidget(self.editTest2, 1, 1, 1, 1)

        self.btnTest3 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest3.setObjectName("btnTest3")
        self.gridVisca.addWidget(self.btnTest3, 2, 0, 1, 1)
        self.editTest3 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest3.setObjectName("editTest3")
        self.gridVisca.addWidget(self.editTest3, 2, 1, 1, 1)

        self.btnTest4 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest4.setObjectName("btnTest4")
        self.gridVisca.addWidget(self.btnTest4, 3, 0, 1, 1)
        self.editTest4 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest4.setObjectName("editTest4")
        self.gridVisca.addWidget(self.editTest4, 3, 1, 1, 1)

        self.btnTest5 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest5.setObjectName("btnTest5")
        self.gridVisca.addWidget(self.btnTest5, 4, 0, 1, 1)
        self.editTest5 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest5.setObjectName("editTest5")
        self.gridVisca.addWidget(self.editTest5, 4, 1, 1, 1)

        self.btnTest6 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest6.setObjectName("btnTest6")
        self.gridVisca.addWidget(self.btnTest6, 5, 0, 1, 1)
        self.editTest6 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest6.setObjectName("editTest6")
        self.gridVisca.addWidget(self.editTest6, 5, 1, 1, 1)

        self.btnTest7 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest7.setObjectName("btnTest7")
        self.gridVisca.addWidget(self.btnTest7, 6, 0, 1, 1)
        self.editTest7 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest7.setObjectName("editTest7")
        self.gridVisca.addWidget(self.editTest7, 6, 1, 1, 1)

        self.btnTest8 = QtWidgets.QPushButton(self.groupVisca)
        self.btnTest8.setObjectName("btnTest8")
        self.gridVisca.addWidget(self.btnTest8, 7, 0, 1, 1)
        self.editTest8 = QtWidgets.QLineEdit(self.groupVisca)
        self.editTest8.setObjectName("editTest8")
        self.gridVisca.addWidget(self.editTest8, 7, 1, 1, 1)

        self.verticalLayoutTest.addWidget(self.groupVisca)
        self.tabTest.setLayout(self.verticalLayoutTest)
        self.tabWidget.addTab(self.tabTest, "")

        self.verticalLayout.addWidget(self.tabWidget)

        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")

        self.labelTx = QtWidgets.QLabel(SerialWidget)
        self.labelTx.setObjectName("labelTx")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTx)

        self.textTx = QtWidgets.QTextEdit(SerialWidget)
        self.textTx.setObjectName("textTx")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textTx)

        self.labelRx = QtWidgets.QLabel(SerialWidget)
        self.labelRx.setObjectName("labelRx")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelRx)

        self.textRx = QtWidgets.QTextEdit(SerialWidget)
        self.textRx.setObjectName("textRx")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textRx)

        self.verticalLayout.addLayout(self.formLayout)

        self.btnClear = QtWidgets.QPushButton(SerialWidget)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout.addWidget(self.btnClear)

        self.retranslateUi(SerialWidget)
        QtCore.QMetaObject.connectSlotsByName(SerialWidget)

    def retranslateUi(self, SerialWidget):
        _translate = QtCore.QCoreApplication.translate
        SerialWidget.setWindowTitle(_translate("SerialWidget", "Serial Tester"))
        self.btnOnline.setText(_translate("SerialWidget", "OnLine"))
        self.labelComPort.setText(_translate("SerialWidget", "ComPort:"))
        self.btnConfigure.setText(_translate("SerialWidget", "Configure"))
        self.labelFw.setText(_translate("SerialWidget", "FW Version:"))
        self.labelFwValue.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("SerialWidget", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTest), _translate("SerialWidget", "Test"))
        self.groupPanTilt.setTitle(_translate("SerialWidget", "Pan/Tilt Control"))
        self.groupMove.setTitle(_translate("SerialWidget", "Continuous Move"))
        self.labelTarget.setText(_translate("SerialWidget", "Target Number"))
        self.labelDome.setText(_translate("SerialWidget", "Dome ID"))
        self.labelFunction.setText(_translate("SerialWidget", "Function Number"))
        self.labelAlarmNumber.setText(_translate("SerialWidget", "Alarm Number"))
        self.labelAlarmType.setText(_translate("SerialWidget", "AlarmType"))
        self.btnSetDefault.setText(_translate("SerialWidget", "Set Default"))
        self.btnSetMove.setText(_translate("SerialWidget", "Set"))
        self.btnClearMove.setText(_translate("SerialWidget", "Clear"))
        self.btnShowSpeed.setText(_translate("SerialWidget", "Show Speed"))
        self.btnStopSpeed.setText(_translate("SerialWidget", "Stop"))
        self.groupVisca.setTitle(_translate("SerialWidget", "Test Visca Commands"))
        self.btnTest1.setText(_translate("SerialWidget", "Test 1"))
        self.btnTest2.setText(_translate("SerialWidget", "Test 2"))
        self.btnTest3.setText(_translate("SerialWidget", "Test 3"))
        self.btnTest4.setText(_translate("SerialWidget", "Test 4"))
        self.btnTest5.setText(_translate("SerialWidget", "Test 5"))
        self.btnTest6.setText(_translate("SerialWidget", "Test 6"))
        self.btnTest7.setText(_translate("SerialWidget", "Test 7"))
        self.btnTest8.setText(_translate("SerialWidget", "Test 8"))
        self.labelTx.setText(_translate("SerialWidget", "Tx:"))
        self.labelRx.setText(_translate("SerialWidget", "Rx:"))
        self.btnClear.setText(_translate("SerialWidget", "Clear"))
