from PyQt5 import QtCore, QtWidgets, QtChart

class Ui_MainTab(object):
    def setupUi(self, MainTab):
        MainTab.setObjectName("MainTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainTab)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.groupPanTilt = QtWidgets.QGroupBox(MainTab)
        self.groupPanTilt.setObjectName("groupPanTilt")
        self.layoutPanTilt = QtWidgets.QVBoxLayout(self.groupPanTilt)
        self.layoutPanTilt.setObjectName("layoutPanTilt")

        self.groupMove = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupMove.setObjectName("groupMove")
        self.gridMove = QtWidgets.QGridLayout(self.groupMove)
        self.gridMove.setObjectName("gridMove")

        self.labelTarget = QtWidgets.QLabel(self.groupMove)
        self.labelTarget.setObjectName("labelTarget")
        self.gridMove.addWidget(self.labelTarget, 0, 0, 1, 1)
        self.spinTarget = QtWidgets.QSpinBox(self.groupMove)
        self.spinTarget.setObjectName("spinTarget")
        self.gridMove.addWidget(self.spinTarget, 0, 1, 1, 1)
        self.labelDome = QtWidgets.QLabel(self.groupMove)
        self.labelDome.setObjectName("labelDome")
        self.gridMove.addWidget(self.labelDome, 0, 2, 1, 1)
        self.spinDome = QtWidgets.QSpinBox(self.groupMove)
        self.spinDome.setObjectName("spinDome")
        self.gridMove.addWidget(self.spinDome, 0, 3, 1, 1)
        self.labelFunction = QtWidgets.QLabel(self.groupMove)
        self.labelFunction.setObjectName("labelFunction")
        self.gridMove.addWidget(self.labelFunction, 0, 4, 1, 1)
        self.spinFunction = QtWidgets.QSpinBox(self.groupMove)
        self.spinFunction.setObjectName("spinFunction")
        self.gridMove.addWidget(self.spinFunction, 0, 5, 1, 1)
        self.labelAlarmNumber = QtWidgets.QLabel(self.groupMove)
        self.labelAlarmNumber.setObjectName("labelAlarmNumber")
        self.gridMove.addWidget(self.labelAlarmNumber, 1, 0, 1, 1)
        self.comboAlarmNumber = QtWidgets.QComboBox(self.groupMove)
        self.comboAlarmNumber.setObjectName("comboAlarmNumber")
        self.gridMove.addWidget(self.comboAlarmNumber, 1, 1, 1, 1)
        self.labelAlarmType = QtWidgets.QLabel(self.groupMove)
        self.labelAlarmType.setObjectName("labelAlarmType")
        self.gridMove.addWidget(self.labelAlarmType, 1, 2, 1, 1)
        self.comboAlarmType = QtWidgets.QComboBox(self.groupMove)
        self.comboAlarmType.setObjectName("comboAlarmType")
        self.gridMove.addWidget(self.comboAlarmType, 1, 3, 1, 1)
        self.btnSetDefault = QtWidgets.QPushButton(self.groupMove)
        self.btnSetDefault.setObjectName("btnSetDefault")
        self.gridMove.addWidget(self.btnSetDefault, 2, 0, 1, 1)
        self.btnSetMove = QtWidgets.QPushButton(self.groupMove)
        self.btnSetMove.setObjectName("btnSetMove")
        self.gridMove.addWidget(self.btnSetMove, 2, 3, 1, 1)
        self.btnClearMove = QtWidgets.QPushButton(self.groupMove)
        self.btnClearMove.setObjectName("btnClearMove")
        self.gridMove.addWidget(self.btnClearMove, 2, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupMove)

        self.groupRelative = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupRelative.setObjectName("groupRelative")
        self.gridRelative = QtWidgets.QGridLayout(self.groupRelative)
        self.gridRelative.setObjectName("gridRelative")
        self.btnRelUp = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelUp.setObjectName("btnRelUp")
        self.gridRelative.addWidget(self.btnRelUp, 0, 1, 1, 1)
        self.btnRelLeft = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelLeft.setObjectName("btnRelLeft")
        self.gridRelative.addWidget(self.btnRelLeft, 1, 0, 1, 1)
        self.btnRelStop = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelStop.setObjectName("btnRelStop")
        self.gridRelative.addWidget(self.btnRelStop, 1, 1, 1, 1)
        self.btnRelRight = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelRight.setObjectName("btnRelRight")
        self.gridRelative.addWidget(self.btnRelRight, 1, 2, 1, 1)
        self.btnRelDown = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelDown.setObjectName("btnRelDown")
        self.gridRelative.addWidget(self.btnRelDown, 2, 1, 1, 1)
        self.labelRelStep = QtWidgets.QLabel(self.groupRelative)
        self.labelRelStep.setObjectName("labelRelStep")
        self.gridRelative.addWidget(self.labelRelStep, 1, 3, 1, 1)
        self.editRelStep = QtWidgets.QLineEdit(self.groupRelative)
        self.editRelStep.setObjectName("editRelStep")
        self.gridRelative.addWidget(self.editRelStep, 1, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupRelative)

        self.groupAbsolute = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupAbsolute.setObjectName("groupAbsolute")
        self.gridAbsolute = QtWidgets.QGridLayout(self.groupAbsolute)
        self.gridAbsolute.setObjectName("gridAbsolute")
        self.btnABS = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABS.setObjectName("btnABS")
        self.gridAbsolute.addWidget(self.btnABS, 0, 0, 1, 1)
        self.editABSPos = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSPos.setObjectName("editABSPos")
        self.gridAbsolute.addWidget(self.editABSPos, 0, 1, 1, 1)
        self.btnABS2 = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABS2.setObjectName("btnABS2")
        self.gridAbsolute.addWidget(self.btnABS2, 1, 0, 1, 1)
        self.editABS2Pos = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABS2Pos.setObjectName("editABS2Pos")
        self.gridAbsolute.addWidget(self.editABS2Pos, 1, 1, 1, 1)
        self.btnABSAngle = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngle.setObjectName("btnABSAngle")
        self.gridAbsolute.addWidget(self.btnABSAngle, 2, 0, 1, 1)
        self.editABSAngle = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSAngle.setObjectName("editABSAngle")
        self.gridAbsolute.addWidget(self.editABSAngle, 2, 1, 1, 1)

        self.layoutPanTilt.addWidget(self.groupAbsolute)

        self.btnHome = QtWidgets.QPushButton(self.groupPanTilt)
        self.btnHome.setObjectName("btnHome")
        self.layoutPanTilt.addWidget(self.btnHome)

        self.horizontalLayout.addWidget(self.groupPanTilt)

        self.layoutChart = QtWidgets.QVBoxLayout()
        self.layoutChart.setObjectName("layoutChart")
        self.chartSpeed = QtChart.QChartView(MainTab)
        self.chartSpeed.setObjectName("chartSpeed")
        self.layoutChart.addWidget(self.chartSpeed)
        self.layoutChartButtons = QtWidgets.QHBoxLayout()
        self.layoutChartButtons.setObjectName("layoutChartButtons")
        self.btnShowSpeed = QtWidgets.QPushButton(MainTab)
        self.btnShowSpeed.setObjectName("btnShowSpeed")
        self.layoutChartButtons.addWidget(self.btnShowSpeed)
        self.btnStopSpeed = QtWidgets.QPushButton(MainTab)
        self.btnStopSpeed.setObjectName("btnStopSpeed")
        self.layoutChartButtons.addWidget(self.btnStopSpeed)
        self.btnClearChart = QtWidgets.QPushButton(MainTab)
        self.btnClearChart.setObjectName("btnClearChart")
        self.layoutChartButtons.addWidget(self.btnClearChart)
        self.layoutChart.addLayout(self.layoutChartButtons)

        self.horizontalLayout.addLayout(self.layoutChart)

        self.retranslateUi(MainTab)
        QtCore.QMetaObject.connectSlotsByName(MainTab)

    def retranslateUi(self, MainTab):
        _translate = QtCore.QCoreApplication.translate
        MainTab.setWindowTitle(_translate("MainTab", "MainTab"))
        self.groupPanTilt.setTitle(_translate("MainTab", "Pan/Tilt Control"))
        self.groupMove.setTitle(_translate("MainTab", "Continuous Move"))
        self.labelTarget.setText(_translate("MainTab", "Target Number"))
        self.labelDome.setText(_translate("MainTab", "Dome ID"))
        self.labelFunction.setText(_translate("MainTab", "Function Number"))
        self.labelAlarmNumber.setText(_translate("MainTab", "Alarm Number"))
        self.labelAlarmType.setText(_translate("MainTab", "AlarmType"))
        self.btnSetDefault.setText(_translate("MainTab", "Set Default"))
        self.btnSetMove.setText(_translate("MainTab", "Set"))
        self.btnClearMove.setText(_translate("MainTab", "Clear"))
        self.groupRelative.setTitle(_translate("MainTab", "Relative Move"))
        self.btnRelUp.setText(_translate("MainTab", "Up"))
        self.btnRelLeft.setText(_translate("MainTab", "Left"))
        self.btnRelStop.setText(_translate("MainTab", "Stop"))
        self.btnRelRight.setText(_translate("MainTab", "Right"))
        self.btnRelDown.setText(_translate("MainTab", "Down"))
        self.labelRelStep.setText(_translate("MainTab", "Step"))
        self.groupAbsolute.setTitle(_translate("MainTab", "Absolute Move"))
        self.btnABS.setText(_translate("MainTab", "ABS"))
        self.btnABS2.setText(_translate("MainTab", "ABS2"))
        self.btnABSAngle.setText(_translate("MainTab", "Angle"))
        self.btnHome.setText(_translate("MainTab", "Home"))
        self.btnShowSpeed.setText(_translate("MainTab", "Show Speed"))
        self.btnStopSpeed.setText(_translate("MainTab", "Stop"))
        self.btnClearChart.setText(_translate("MainTab", "Clear Chart"))
