from PyQt5 import QtCore, QtWidgets, QtChart

class Ui_MainTab(object):
    def setupUi(self, MainTab):
        MainTab.setObjectName("MainTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainTab)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.groupPanTilt = QtWidgets.QGroupBox(MainTab)
        self.groupPanTilt.setObjectName("groupPanTilt")
        self.layoutPanTilt = QtWidgets.QVBoxLayout(self.groupPanTilt)
        self.layoutPanTilt.setObjectName("layoutPanTilt")

        self.groupMove = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupMove.setObjectName("groupMove")
        self.gridMove = QtWidgets.QGridLayout(self.groupMove)
        self.gridMove.setObjectName("gridMove")
        self.btnPanLeft = QtWidgets.QPushButton(self.groupMove)
        self.btnPanLeft.setObjectName("btnPanLeft")
        self.gridMove.addWidget(self.btnPanLeft, 1, 0, 1, 1)
        self.btnPanStop = QtWidgets.QPushButton(self.groupMove)
        self.btnPanStop.setObjectName("btnPanStop")
        self.gridMove.addWidget(self.btnPanStop, 1, 1, 1, 1)
        self.btnPanRight = QtWidgets.QPushButton(self.groupMove)
        self.btnPanRight.setObjectName("btnPanRight")
        self.gridMove.addWidget(self.btnPanRight, 1, 2, 1, 1)
        self.btnTiltUp = QtWidgets.QPushButton(self.groupMove)
        self.btnTiltUp.setObjectName("btnTiltUp")
        self.gridMove.addWidget(self.btnTiltUp, 0, 1, 1, 1)
        self.btnTiltDown = QtWidgets.QPushButton(self.groupMove)
        self.btnTiltDown.setObjectName("btnTiltDown")
        self.gridMove.addWidget(self.btnTiltDown, 2, 1, 1, 1)
        self.checkMoveStop = QtWidgets.QCheckBox(self.groupMove)
        self.checkMoveStop.setObjectName("checkMoveStop")
        self.gridMove.addWidget(self.checkMoveStop, 0, 3, 1, 2)
        self.btnStopAt = QtWidgets.QPushButton(self.groupMove)
        self.btnStopAt.setObjectName("btnStopAt")
        self.gridMove.addWidget(self.btnStopAt, 1, 4, 1, 1)
        self.editStopAt = QtWidgets.QLineEdit(self.groupMove)
        self.editStopAt.setObjectName("editStopAt")
        self.gridMove.addWidget(self.editStopAt, 2, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupMove)

        self.groupAbsolute = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupAbsolute.setObjectName("groupAbsolute")
        self.gridAbsolute = QtWidgets.QGridLayout(self.groupAbsolute)
        self.gridAbsolute.setObjectName("gridAbsolute")
        self.btnABS = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABS.setObjectName("btnABS")
        self.gridAbsolute.addWidget(self.btnABS, 0, 0, 1, 1)
        self.editABSPos = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSPos.setObjectName("editABSPos")
        self.gridAbsolute.addWidget(self.editABSPos, 0, 1, 1, 1)
        self.btnABS2 = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABS2.setObjectName("btnABS2")
        self.gridAbsolute.addWidget(self.btnABS2, 1, 0, 1, 1)
        self.editABS2Pos = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABS2Pos.setObjectName("editABS2Pos")
        self.gridAbsolute.addWidget(self.editABS2Pos, 1, 1, 1, 1)
        self.btnABSAngle = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngle.setObjectName("btnABSAngle")
        self.gridAbsolute.addWidget(self.btnABSAngle, 2, 0, 1, 1)
        self.editABSAngle = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSAngle.setObjectName("editABSAngle")
        self.gridAbsolute.addWidget(self.editABSAngle, 2, 1, 1, 1)
        self.btnABSAngle2 = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngle2.setObjectName("btnABSAngle2")
        self.gridAbsolute.addWidget(self.btnABSAngle2, 3, 0, 1, 1)
        self.editABSAngle2 = QtWidgets.QLineEdit(self.groupAbsolute)
        self.editABSAngle2.setObjectName("editABSAngle2")
        self.gridAbsolute.addWidget(self.editABSAngle2, 3, 1, 1, 1)
        self.btnABSStop = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSStop.setObjectName("btnABSStop")
        self.gridAbsolute.addWidget(self.btnABSStop, 4, 0, 1, 2)
        self.layoutPanType = QtWidgets.QHBoxLayout()
        self.layoutPanType.setObjectName("layoutPanType")
        self.btnPanType = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnPanType.setObjectName("btnPanType")
        self.layoutPanType.addWidget(self.btnPanType)
        self.comboPanMethod = QtWidgets.QComboBox(self.groupAbsolute)
        self.comboPanMethod.setObjectName("comboPanMethod")
        self.comboPanMethod.addItems(["Shorter Path", "Forced CW", "Forced CCW"])
        self.layoutPanType.addWidget(self.comboPanMethod)
        self.gridAbsolute.addLayout(self.layoutPanType, 5, 0, 1, 2)
        self.btnABSAngleStop = QtWidgets.QPushButton(self.groupAbsolute)
        self.btnABSAngleStop.setObjectName("btnABSAngleStop")
        self.gridAbsolute.addWidget(self.btnABSAngleStop, 6, 0, 1, 2)

        self.layoutPanTilt.addWidget(self.groupAbsolute)

        self.groupRelative = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupRelative.setObjectName("groupRelative")
        self.gridRelative = QtWidgets.QGridLayout(self.groupRelative)
        self.gridRelative.setObjectName("gridRelative")
        self.btnRelUp = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelUp.setObjectName("btnRelUp")
        self.gridRelative.addWidget(self.btnRelUp, 0, 1, 1, 1)
        self.btnRelLeft = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelLeft.setObjectName("btnRelLeft")
        self.gridRelative.addWidget(self.btnRelLeft, 1, 0, 1, 1)
        self.btnRelStop = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelStop.setObjectName("btnRelStop")
        self.gridRelative.addWidget(self.btnRelStop, 1, 1, 1, 1)
        self.btnRelRight = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelRight.setObjectName("btnRelRight")
        self.gridRelative.addWidget(self.btnRelRight, 1, 2, 1, 1)
        self.btnRelDown = QtWidgets.QPushButton(self.groupRelative)
        self.btnRelDown.setObjectName("btnRelDown")
        self.gridRelative.addWidget(self.btnRelDown, 2, 1, 1, 1)
        self.labelRelStep = QtWidgets.QLabel(self.groupRelative)
        self.labelRelStep.setObjectName("labelRelStep")
        self.gridRelative.addWidget(self.labelRelStep, 1, 3, 1, 1)
        self.editRelStep = QtWidgets.QLineEdit(self.groupRelative)
        self.editRelStep.setObjectName("editRelStep")
        self.gridRelative.addWidget(self.editRelStep, 1, 4, 1, 1)

        self.layoutPanTilt.addWidget(self.groupRelative)

        self.groupStall = QtWidgets.QGroupBox(self.groupPanTilt)
        self.groupStall.setObjectName("groupStall")
        self.layoutStall = QtWidgets.QHBoxLayout(self.groupStall)
        self.layoutStall.setObjectName("layoutStall")
        self.btnStallCaliOn = QtWidgets.QPushButton(self.groupStall)
        self.btnStallCaliOn.setObjectName("btnStallCaliOn")
        self.layoutStall.addWidget(self.btnStallCaliOn)
        self.btnStallCaliOff = QtWidgets.QPushButton(self.groupStall)
        self.btnStallCaliOff.setObjectName("btnStallCaliOff")
        self.layoutStall.addWidget(self.btnStallCaliOff)

        self.layoutPanTilt.addWidget(self.groupStall)

        self.btnHome = QtWidgets.QPushButton(self.groupPanTilt)
        self.btnHome.setObjectName("btnHome")
        self.layoutPanTilt.addWidget(self.btnHome)

        self.horizontalLayout.addWidget(self.groupPanTilt)

        self.layoutChart = QtWidgets.QVBoxLayout()
        self.layoutChart.setObjectName("layoutChart")
        self.chartSpeed = QtChart.QChartView(MainTab)
        self.chartSpeed.setObjectName("chartSpeed")
        self.layoutChart.addWidget(self.chartSpeed)
        self.layoutChartButtons = QtWidgets.QHBoxLayout()
        self.layoutChartButtons.setObjectName("layoutChartButtons")
        self.btnShowSpeed = QtWidgets.QPushButton(MainTab)
        self.btnShowSpeed.setObjectName("btnShowSpeed")
        self.layoutChartButtons.addWidget(self.btnShowSpeed)
        self.btnStopSpeed = QtWidgets.QPushButton(MainTab)
        self.btnStopSpeed.setObjectName("btnStopSpeed")
        self.layoutChartButtons.addWidget(self.btnStopSpeed)
        self.btnClearChart = QtWidgets.QPushButton(MainTab)
        self.btnClearChart.setObjectName("btnClearChart")
        self.layoutChartButtons.addWidget(self.btnClearChart)
        self.layoutChart.addLayout(self.layoutChartButtons)

        self.horizontalLayout.addLayout(self.layoutChart)

        self.retranslateUi(MainTab)
        QtCore.QMetaObject.connectSlotsByName(MainTab)

    def retranslateUi(self, MainTab):
        _translate = QtCore.QCoreApplication.translate
        MainTab.setWindowTitle(_translate("MainTab", "MainTab"))
        self.groupPanTilt.setTitle(_translate("MainTab", "Pan/Tilt Control"))
        self.groupMove.setTitle(_translate("MainTab", "Continuous Move"))
        self.btnPanLeft.setText(_translate("MainTab", "Left"))
        self.btnPanStop.setText(_translate("MainTab", "Stop"))
        self.btnPanRight.setText(_translate("MainTab", "Right"))
        self.btnTiltUp.setText(_translate("MainTab", "Up"))
        self.btnTiltDown.setText(_translate("MainTab", "Down"))
        self.checkMoveStop.setText(_translate("MainTab", "Move+Stop"))
        self.btnStopAt.setText(_translate("MainTab", "Stop At"))

        self.groupAbsolute.setTitle(_translate("MainTab", "Absolute Move"))
        self.btnABS.setText(_translate("MainTab", "ABS"))
        self.btnABS2.setText(_translate("MainTab", "ABS2"))
        self.btnABSAngle.setText(_translate("MainTab", "Angle"))
        self.btnABSAngle2.setText(_translate("MainTab", "Angle2"))
        self.btnABSStop.setText(_translate("MainTab", "ABS Stop"))
        self.btnPanType.setText(_translate("MainTab", "Get Pan Type"))
        self.btnABSAngleStop.setText(_translate("MainTab", "ABS Angle Stop"))

        self.groupRelative.setTitle(_translate("MainTab", "Relative Move"))
        self.btnRelUp.setText(_translate("MainTab", "Up"))
        self.btnRelLeft.setText(_translate("MainTab", "Left"))
        self.btnRelStop.setText(_translate("MainTab", "Stop"))
        self.btnRelRight.setText(_translate("MainTab", "Right"))
        self.btnRelDown.setText(_translate("MainTab", "Down"))
        self.labelRelStep.setText(_translate("MainTab", "Step"))

        self.groupStall.setTitle(_translate("MainTab", "Stall Cali."))
        self.btnStallCaliOn.setText(_translate("MainTab", "On"))
        self.btnStallCaliOff.setText(_translate("MainTab", "Off"))

        self.btnHome.setText(_translate("MainTab", "Home"))
        self.btnShowSpeed.setText(_translate("MainTab", "Show Speed"))
        self.btnStopSpeed.setText(_translate("MainTab", "Stop"))
        self.btnClearChart.setText(_translate("MainTab", "Clear Chart"))
